# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

Cuerda6 = B1  
# (Si1) - MIDI 23  
Cuerda5 = E1  
# (Mi1) - MIDI 28  
Cuerda4 = A1  
# (La1) - MIDI 33  
Cuerda3 = D2  
# (Re2) - MIDI 38  
Cuerda2 = G2  
# (Sol2) - MIDI 43  