# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

Cuerda5 = G5  
# (Sol5) - MIDI 79  
Cuerda4 = C3  
# (Do3) - MIDI 48  
Cuerda3 = G3  
# (Sol3) - MIDI 55  
Cuerda2 = D4  
# (Re4) - MIDI 62  
Cuerda1 = A4  
# (La4) - MIDI 69  