# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
Cuerda6 = E2 
# (Mi2) - MIDI 40
Cuerda5 = A2 
# (La2) - MIDI 45
Cuerda4 = D3 
# (Re3) - MIDI 50
Cuerda3 = G3 
# (Sol3) - MIDI 55
Cuerda2 = B3 
# (Si3) - MIDI 59
Cuerda1 = E4 
# (Mi4) - MIDI 64

Modo = L
Tramos = 5