# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

Cuerda6 = E2  
# (Mi2) - MIDI 40  
Cuerda5 = A2  
# (La2) - MIDI 45  
Cuerda4 = E3  
# (Mi3) - MIDI 52  
Cuerda3 = A3  
# (La3) - MIDI 57  
Cuerda2 = C#4  
# (Do#4) - MIDI 61  
Cuerda1 = E4  
# (Mi4) - MIDI 64  
