# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

midi.port.cant=6
midi.ports=ALL
//ALL, default
midi.port.default=guitarra
//nombre del puerto hasta 6 puertos
midi.port.1=1
midi.port.2=2
midi.port.3=3
midi.port.4=4
midi.port.5=5
midi.port.6=6


//numero del puerto al que va cada cuerda
midi.port.String.6=1
midi.port.String.5=2
midi.port.String.4=1
midi.port.String.3=2
midi.port.String.2=1
midi.port.String.1=2


//canal por el que sale cada cuerda
midi.chanel.String.6=6
midi.chanel.String.5=5
midi.chanel.String.4=4
midi.chanel.String.3=3
midi.chanel.String.2=2
midi.chanel.String.1=1
