# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

midi.port.cant=6
midi.port.default=LoopBe
midi.port.1=cuerda1
midi.port.2=cuerda2
midi.port.3=cuerda3
midi.port.4=cuerda4
midi.port.5=cuerda5
midi.port.6=cuerda6


midi.port.String.lowE=1
midi.port.String.A=2
midi.port.String.D=1
midi.port.String.G=2
midi.port.String.B=1
midi.port.String.highE=2

midi.chanel.String.lowE=6
midi.chanel.String.A=5
midi.chanel.String.D=4
midi.chanel.String.G=3
midi.chanel.String.B=2
midi.chanel.String.highE=1