string.initial.value.lowE=40
string.initial.value.A=45
string.initial.value.D=50
string.initial.value.G=55
string.initial.value.B=59
string.initial.value.highE=64


string.initial.channel.lowE=1
string.initial.channel.A=2
string.initial.channel.D=3
string.initial.channel.G=4
string.initial.channel.B=5
string.initial.channel.highE=6

string.strength.max=100
string.strength.min=100
string_strength_var=5

control.slide.wheel=s
control.slide.wheel.variation=5
control.slide.up=33
control.slide.down=33
control.slide=33
control.slide.onNote=no

control.bend.wheel=s
control.bend.wheel.variation=5
control.bend.wheel.tones=2
control.bend.unibend=28
control.bend.up=33
control.bend.down=-10