VST=amp

control_bend_down=-10
control_bend_unibend=28
control_bend_up=29
control_bend_wheel_tones=2
control_bend_wheel_variation=16
control_bend_wheel=s
control_hammer_on_keyswitch=n
control_hammer_on_release_after_play=s
control_hammer_on_stop=31
control_hammer_on_strength=50
control_hammer_on_value=30
control_mute_note_value=38
control_mute_note=s
control_pull_hammer_down=30
control_pull_hammer_onNote=s
control_pull_hammer_up=31
control_pull_hammer_wheel_variation=5
control_pull_hammer_wheel=n
control_pull_off_keyswitch=n
control_pull_off_release_after_play=s
control_pull_off_stop=31
control_pull_off_strength=50
control_pull_off_value=32
control_slide_down=111
control_slide_onNote=s
control_slide_sustainPedal=n
control_slide_up=114
control_slide_wheel_variation=16
control_slide_wheel=n
control_string_muteOnRelease=s
control_tremolo_wheel_tones=1
port_signal_sending_all=n
port_signal_sending_quantity=2
port_signal_sending_rotative=s
string_bend_strength=110
string_cc_selection_value_A=42
string_cc_selection_value_B=105
string_cc_selection_value_D=63
string_cc_selection_value_G=84
string_cc_selection_value_highE=127
string_cc_selection_value_lowE=21
string_cc_selection=s
string_cutAlways=n
string_initial_channel_A=5
string_initial_channel_B=2
string_initial_channel_D=4
string_initial_channel_G=3
string_initial_channel_highE=1
string_initial_channel_lowE=6
string_initial_value_A=45
string_initial_value_B=59
string_initial_value_D=50
string_initial_value_G=55
string_initial_value_highE=64
string_initial_value_lowE=40
string_key_selection_value_A=33
string_key_selection_value_B=31
string_key_selection_value_D=26
string_key_selection_value_G=31
string_key_selection_value_highE=31
string_key_selection_value_lowE=28
string_key_selection=n
string_strength_max=100
string_strength_min=80
string_strength_var=20
