string.initial.value.lowE=40
string.initial.value.A=45
string.initial.value.D=50
string.initial.value.G=55
string.initial.value.B=59
string.initial.value.highE=64

string.initial.channel.lowE=6
string.initial.channel.A=5
string.initial.channel.D=4
string.initial.channel.G=3
string.initial.channel.B=2
string.initial.channel.highE=1

    
string.cc.selection.value.lowE=21
string.cc.selection.value.A=42
string.cc.selection.value.D=63
string.cc.selection.value.G=84
string.cc.selection.value.B=105
string.cc.selection.value.highE=126

string.strength.max=110
string.strength.min=110
string.strength.1.max=40
string.strength.1.min=127
string.strength.2.max=50
string.strength.2.min=50
string.strength.3.max=110
string.strength.3.min=110


string.strength.var=20

control.string.muteOnRelease=s

control.slide.wheel=s
control.slide.wheel.variation=16
control.slide.up=31
control.slide.down=30
control.slide.onNote=s
control.bend.wheel=s
control.bend.wheel.variation=16
control.bend.wheel.tones=2
control.bend.unibend=28
control.bend.up=29
control.bend.down=-10
control.tremolo.wheel.tones=1
control.mute.note=si
control.mute.note.value=38

port.signal.sending.all=n
port.signal.sending.rotative=s
port.signal.sending.quantity=2
