driver.quantity=5
driver.model.1=realGuitar
driver.model.2=bajoNI
driver.model.3=guitarraElec
driver.model.4=ukeleleac6
driver.model.5=acou6tic


midi.port.cant=6
midi.port.default=LoopBe
midi.port.1=myMidiPort1
midi.port.2=myMidiPort2
midi.port.3=myMidiPort3
midi.port.4=myMidiPort4
midi.port.5=myMidiPort5
midi.port.6=myMidiPort6

midi.port.String.lowE=1
midi.port.String.A=2
midi.port.String.D=1
midi.port.String.G=2
midi.port.String.B=1
midi.port.String.highE=2


general.btns.save=y
general.btns.load=y